# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc4d21d889cecd144e5998162052b93c32c5913fcc4c74da48ca73672c429c97df944720409f4873ad8d476942bd865f2677d0ffa4cde4f0489c7b28a87a97a1

test:
  secret_key_base: 997ad613316831611f5cbe0bad3e94d3185f189cbe36fa6e9ad8e15346966d1f7fe78bf2e51c4fb49eb117df4a637b4592a5d8e55e311d7f60205e71076c35fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
